export const stateToKeyMap: Record<string, string> = {
  Acre: "br-ac",
  Alagoas: "br-al",
  Amapá: "br-ap",
  Amazonas: "br-am",
  Bahia: "br-ba",
  Ceará: "br-ce",
  "Distrito Federal": "br-df",
  "Espírito Santo": "br-es",
  Goiás: "br-go",
  Maranhão: "br-ma",
  "Mato Grosso": "br-mt",
  "Mato Grosso do Sul": "br-ms",
  "Minas Gerais": "br-mg",
  Pará: "br-pa",
  Paraíba: "br-pb",
  Paraná: "br-pr",
  Pernambuco: "br-pe",
  Piauí: "br-pi",
  "Rio de Janeiro": "br-rj",
  "Rio Grande do Norte": "br-rn",
  "Rio Grande do Sul": "br-rs",
  Rondônia: "br-ro",
  Roraima: "br-rr",
  "Santa Catarina": "br-sc",
  "São Paulo": "br-sp",
  Sergipe: "br-se",
  Tocantins: "br-to",
};
